path_charge_to_up:
    p1: [2.0, -0.43, 0]
    p2: [2.5, -0.43, 0]
    p3: [4.5, -0.44, 0]
    p4: [5.0, -0.45, 0]
path_up_to_charge:
    p1: [2.0, -0.43, 0]
    p2: [2.5, -0.43, 0]
    p3: [4.5, -0.44, 0]
    p4: [5.0, -0.45, 0]
path_down_to_up:
    p1: [5.8, 2.0, 180]
path_up_to_down:
    p1: [2.05, 2.0, 180]
