path_charge_to_up:
    p02: [-1.04, -2.23, 90]
path_up_to_charge:
    p01: [-1.04, -2.23, 90]
    p02: [-1.02, -2.2, 0]
path_up_to_down1:
    p01: [-1.04, -2.23, 90]
    p02: [-1.17, 1.27, 90]
    p03: [3.98, 1.45, 180]
    p04: [8.5, 1.39, 0] 
path_down1_to_down2_:
    p01: [0,0,0]
path_down2_to_down3_:
    p01: [0,0,0]
path_down3_to_down4_:
    p01: [0,0,0]
path_down1_to_up:
    p01: [7.84, 1.36, 0]
    p02: [3.53, 1.38, 0]
    p03: [-1.05, 1.17, 180]
    p04: [-1.04, -2.23, 90]                
path_down2_to_up:
    p01: [0,0,0]
path_down3_to_up:
    p01: [0,0,0]
path_down4_to_up:
    p01: [0,0,0]



